In [1]:
import numpy as np
import cvxpy as cp
import matplotlib.pyplot as plt

In [2]:
'''
SDP of form
    minimize tr(CX)
    subject to tr(A_iX) = b_i, i=1,...,p
    X PSD
Variable - X
Problem data - S^n (set of nxn symm matrices)
            C, A_1,...,A_p \in S^n
            b_1,...,b_p \in \R
''' 

# generate random SDP
n = 3
p = 3
np.random.seed(1)
C = np.random.randn(n,n)
A = [] # conditions
b = []
for i in range(p):
    A.append(np.random.randn(n,n))
    b.append(np.random.randn())

# symmetric matrix
X = cp.Variable((n,n), symmetric=True)
constraints = [X >> 0]
constraints += [cp.trace(A[i]@X) == b[i] for i in range(p)]
prob = cp.Problem(cp.Minimize(cp.trace(C@X)), constraints)
prob.solve()

print(prob.value) # optimal value
print(X.value) # solution X


2.654351510231603
[[ 1.60805795 -0.59770492 -0.69576152]
 [-0.59770492  0.22229041  0.24689363]
 [-0.69576152  0.24689363  1.39679885]]


In [3]:
print(np.trace(A[0]@X.value))
print(b[0])
lams, V = np.linalg.eig(X.value)
print(lams)

0.04221368446072571
0.04221374671559283
[2.38287761e+00 8.44267838e-01 1.76352325e-06]
